apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: fluentd-gcp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-gcp
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - watch
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-gcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-gcp
subjects:
- kind: ServiceAccount
  name: fluentd-gcp
